package com.sys.incubator.Entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.*;
import java.util.List;

@Data
@Entity
@AllArgsConstructor
@NoArgsConstructor
public class Incubator {
    //id
    @Id
    //autogenerated
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    private String location, address,firstName,lastName,phone,latitude,longitude;
    private String temperature,humidity,batteryVoltage,batteryCurrent;
    private String state;
    private String dateAdded;

    @Transient
    private List<Messages> messagesList;
}
